"""
Planning Subsystem Data Models and Status Enums.
"""

from dataclasses import dataclass, field
from enum import Enum
from typing import Any


class StepStatus(str, Enum):
    """Execution status of an individual plan step."""

    PENDING = "PENDING"
    RUNNING = "RUNNING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"
    SKIPPED = "SKIPPED"


@dataclass
class PlanStep:
    """Single executable step in a multi-step task plan."""

    step_id: int
    tool_name: str
    arguments: dict[str, Any] = field(default_factory=dict)
    description: str = ""
    status: StepStatus = StepStatus.PENDING
    result_message: str | None = None


@dataclass
class Plan:
    """Multi-step execution plan generated by the LLM / TaskPlanner."""

    plan_id: str
    objective: str
    steps: list[PlanStep] = field(default_factory=list)
    is_valid: bool = True
    validation_error: str | None = None
